export type SeedJoke = {
  setup: string;
  punchline: string;
  rating: "clean" | "adult";
  category: string;
};

export const SEED_JOKES: SeedJoke[] = [
  { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything.", rating: "clean", category: "science" },
  { setup: "I told my wife she was drawing her eyebrows too high.", punchline: "She looked surprised.", rating: "clean", category: "one-liner" },
  { setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field.", rating: "clean", category: "dad" },
  { setup: "I'm reading a book about anti-gravity.", punchline: "It's impossible to put down.", rating: "clean", category: "dad" },
  { setup: "What do you call a fake noodle?", punchline: "An impasta.", rating: "clean", category: "food" },
  { setup: "Why don't eggs tell jokes?", punchline: "They'd crack each other up.", rating: "clean", category: "food" },
  { setup: "What's brown and sticky?", punchline: "A stick.", rating: "clean", category: "dad" },
  { setup: "I would tell you a construction joke.", punchline: "But I'm still working on it.", rating: "clean", category: "dad" },
  { setup: "Why can't your nose be 12 inches long?", punchline: "Because then it would be a foot.", rating: "clean", category: "dad" },
  { setup: "What did the ocean say to the beach?", punchline: "Nothing, it just waved.", rating: "clean", category: "dad" },
  { setup: "Why did the bicycle fall over?", punchline: "It was two-tired.", rating: "clean", category: "dad" },
  { setup: "How does a penguin build its house?", punchline: "Igloos it together.", rating: "clean", category: "animals" },
  { setup: "What do you call a belt made of watches?", punchline: "A waist of time.", rating: "clean", category: "dad" },
  { setup: "Why did the coffee file a police report?", punchline: "It got mugged.", rating: "clean", category: "food" },
  { setup: "What do you call an alligator in a vest?", punchline: "An investigator.", rating: "clean", category: "animals" },
  { setup: "I used to play piano by ear.", punchline: "Now I use my hands.", rating: "clean", category: "music" },
  { setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts.", rating: "clean", category: "halloween" },
  { setup: "What did one wall say to the other?", punchline: "I'll meet you at the corner.", rating: "clean", category: "dad" },
  { setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one.", rating: "clean", category: "sports" },
  { setup: "What's the best thing about Switzerland?", punchline: "I don't know, but the flag is a big plus.", rating: "clean", category: "travel" },
  { setup: "I asked the librarian if the library had books on paranoia.", punchline: "She whispered, 'They're right behind you.'", rating: "clean", category: "books" },
  { setup: "Why did the math book look so sad?", punchline: "It had too many problems.", rating: "clean", category: "school" },
  { setup: "What do you call a bear with no teeth?", punchline: "A gummy bear.", rating: "clean", category: "animals" },
  { setup: "Why can't you give Elsa a balloon?", punchline: "Because she will let it go.", rating: "clean", category: "movies" },
  { setup: "How do you organize a space party?", punchline: "You planet.", rating: "clean", category: "science" },
  { setup: "What did the zero say to the eight?", punchline: "Nice belt.", rating: "clean", category: "school" },
  { setup: "Why did the tomato blush?", punchline: "Because it saw the salad dressing.", rating: "clean", category: "food" },
  { setup: "What's orange and sounds like a parrot?", punchline: "A carrot.", rating: "clean", category: "food" },
  { setup: "I only know 25 letters of the alphabet.", punchline: "I don't know y.", rating: "clean", category: "school" },
  { setup: "What do you call cheese that isn't yours?", punchline: "Nacho cheese.", rating: "clean", category: "food" },
  { setup: "Why did the cookie go to the doctor?", punchline: "It felt crumby.", rating: "clean", category: "food" },
  { setup: "What has ears but cannot hear?", punchline: "A cornfield.", rating: "clean", category: "riddle" },
  { setup: "Why did the stadium get hot after the game?", punchline: "All the fans left.", rating: "clean", category: "sports" },
  { setup: "What do you call a sleeping bull?", punchline: "A bulldozer.", rating: "clean", category: "animals" },
  { setup: "Why don't some couples go to the gym?", punchline: "Because some relationships don't work out.", rating: "clean", category: "one-liner" },
  { setup: "I told my computer I needed a break.", punchline: "Now it won't stop sending me KitKats.", rating: "clean", category: "tech" },
  { setup: "Why was the broom late?", punchline: "It over-swept.", rating: "clean", category: "dad" },
  { setup: "What do you call a pile of cats?", punchline: "A meowtain.", rating: "clean", category: "animals" },
  { setup: "Why did the banana go to the doctor?", punchline: "It wasn't peeling well.", rating: "clean", category: "food" },
  { setup: "What's a skeleton's favorite instrument?", punchline: "The trom-bone.", rating: "clean", category: "halloween" },
  { setup: "I used to be a baker.", punchline: "But I couldn't make enough dough.", rating: "clean", category: "food" },
  { setup: "Why did the invisible man turn down the job offer?", punchline: "He just couldn't see himself doing it.", rating: "clean", category: "one-liner" },
  { setup: "What do you call a factory that makes okay products?", punchline: "A satisfactory.", rating: "clean", category: "dad" },
  { setup: "Why did the chicken join a band?", punchline: "Because it had the drumsticks.", rating: "clean", category: "music" },
  { setup: "How does a scientist freshen her breath?", punchline: "With experi-mints.", rating: "clean", category: "science" },
  { setup: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!", rating: "clean", category: "dad" },
  { setup: "Why can't a leopard hide?", punchline: "Because he's always spotted.", rating: "clean", category: "animals" },
  { setup: "What do you call a fish without eyes?", punchline: "Fsh.", rating: "clean", category: "animals" },
  { setup: "I would tell you a chemistry joke.", punchline: "But I know I wouldn't get a reaction.", rating: "clean", category: "science" },
  { setup: "Why did the grape stop in the middle of the road?", punchline: "Because it ran out of juice.", rating: "clean", category: "food" },
  { setup: "What's the difference between a poorly dressed man on a trampoline and a well-dressed man on a trampoline?", punchline: "Attire.", rating: "clean", category: "wordplay" },
  { setup: "Why don't oysters donate to charity?", punchline: "Because they are shellfish.", rating: "clean", category: "animals" },
  { setup: "What did the buffalo say when his son left for college?", punchline: "Bison.", rating: "clean", category: "animals" },
  { setup: "I named my dog Five Miles.", punchline: "So I can say I walk Five Miles every day.", rating: "clean", category: "animals" },
  { setup: "Why did the can crusher quit his job?", punchline: "Because it was soda pressing.", rating: "clean", category: "dad" },
  { setup: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman.", rating: "clean", category: "holiday" },
  { setup: "Why did the cowboy buy a dachshund?", punchline: "He wanted to get a long little doggie.", rating: "clean", category: "animals" },
  { setup: "What's red and bad for your teeth?", punchline: "A brick.", rating: "clean", category: "one-liner" },
  { setup: "I threw a boomerang a few years ago.", punchline: "I now live in constant fear.", rating: "clean", category: "one-liner" },
  { setup: "Why did the man run around his bed?", punchline: "He wanted to catch up on his sleep.", rating: "clean", category: "dad" },
  { setup: "What do you call a cow with no legs?", punchline: "Ground beef.", rating: "clean", category: "animals" },
  { setup: "Why was the equal sign so humble?", punchline: "It knew it wasn't less than or greater than anyone else.", rating: "clean", category: "school" },
  { setup: "What did the left eye say to the right eye?", punchline: "Between us, something smells.", rating: "clean", category: "dad" },
  { setup: "Why do bees have sticky hair?", punchline: "They use honeycombs.", rating: "clean", category: "animals" },
  { setup: "I told my suitcase there will be no vacation this year.", punchline: "Now we're having a real falling-out.", rating: "clean", category: "travel" },
  { setup: "What's the difference between a hippo and a zippo?", punchline: "One is really heavy, the other is a little lighter.", rating: "clean", category: "wordplay" },
  { setup: "Why did the calendar get a bad grade?", punchline: "Its days were numbered.", rating: "clean", category: "dad" },
  { setup: "What do you call a sad cup of coffee?", punchline: "Depresso.", rating: "clean", category: "food" },
  { setup: "I used to hate facial hair.", punchline: "But then it grew on me.", rating: "clean", category: "one-liner" },
  { setup: "Why did the scarecrow become a successful neurosurgeon?", punchline: "He was outstanding in his field, then he switched.", rating: "clean", category: "dad" },
  { setup: "What do you get when you cross a snowman and a vampire?", punchline: "Frostbite.", rating: "clean", category: "holiday" },
  { setup: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they'd be bagels.", rating: "clean", category: "animals" },
  { setup: "I asked my dog what's two minus two.", punchline: "He said nothing.", rating: "clean", category: "animals" },
  { setup: "What's a pirate's favorite letter?", punchline: "You think it's R, but it's the C.", rating: "clean", category: "wordplay" },
  { setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes.", rating: "clean", category: "music" },
  { setup: "What kind of shoes do spies wear?", punchline: "Sneakers.", rating: "clean", category: "dad" },
  { setup: "I started a band called 999 Megabytes.", punchline: "We still haven't got a gig.", rating: "clean", category: "tech" },
  { setup: "Why was six afraid of seven?", punchline: "Because seven eight nine.", rating: "clean", category: "school" },
  { setup: "What do you call a boomerang that doesn't come back?", punchline: "A stick.", rating: "clean", category: "dad" },
  { setup: "Why did the chicken cross the playground?", punchline: "To get to the other slide.", rating: "clean", category: "kids" },
  { setup: "I bought some shoes from a drug dealer.", punchline: "I don't know what he laced them with, but I was tripping all day.", rating: "clean", category: "one-liner" },
  { setup: "What's the loudest kind of frozen water?", punchline: "An ice-scream.", rating: "clean", category: "food" },
  { setup: "Why don't mountains get cold in winter?", punchline: "They wear snowcaps.", rating: "clean", category: "dad" },
  { setup: "What did the grape do when it got stepped on?", punchline: "It let out a little wine.", rating: "clean", category: "food" },
  { setup: "Why did the teddy bear say no to dessert?", punchline: "It was stuffed.", rating: "clean", category: "kids" },
  { setup: "How do you make a tissue dance?", punchline: "Put a little boogie in it.", rating: "clean", category: "dad" },
  { setup: "What do you call a parade of rabbits hopping backwards?", punchline: "A receding hare-line.", rating: "clean", category: "animals" },
  { setup: "Why did the coffee taste like dirt?", punchline: "It was ground this morning.", rating: "clean", category: "food" },
  { setup: "I told a joke about a broken pencil.", punchline: "There was no point.", rating: "clean", category: "dad" },
  { setup: "What has four wheels and flies?", punchline: "A garbage truck.", rating: "clean", category: "riddle" },
  { setup: "Why did the man put his money in the freezer?", punchline: "He wanted cold hard cash.", rating: "clean", category: "dad" },
  { setup: "What's a vampire's favorite fruit?", punchline: "A neck-tarine.", rating: "clean", category: "halloween" },
  { setup: "I used to be addicted to the hokey pokey.", punchline: "But then I turned myself around.", rating: "clean", category: "one-liner" },
  { setup: "Why did the cookie cry?", punchline: "Because its mom was a wafer so long.", rating: "clean", category: "food" },
  { setup: "What do you call a magician's dog?", punchline: "A labracadabrador.", rating: "clean", category: "animals" },
  { setup: "Why can't you hear a pterodactyl go to the bathroom?", punchline: "Because the P is silent.", rating: "clean", category: "school" },
  { setup: "I invented a new word.", punchline: "Plagiarism.", rating: "clean", category: "one-liner" },
  { setup: "What do you call an illegally parked frog?", punchline: "Toad.", rating: "clean", category: "animals" },
  { setup: "Why did the ghost go to the party?", punchline: "For the boos.", rating: "clean", category: "halloween" },
  { setup: "What's the difference between a cat and a comma?", punchline: "A cat has claws at the end of its paws, a comma is a pause at the end of a clause.", rating: "clean", category: "wordplay" },
  { setup: "I told my wife she should embrace her mistakes.", punchline: "She hugged me.", rating: "clean", category: "one-liner" },
  { setup: "Why did the computer go to therapy?", punchline: "It had too many bytes of emotional baggage.", rating: "clean", category: "tech" },
  { setup: "What do you call two birds in love?", punchline: "Tweethearts.", rating: "clean", category: "animals" },
  { setup: "Why do programmers prefer dark mode?", punchline: "Because light attracts bugs.", rating: "clean", category: "tech" },
  { setup: "How do you throw a space party?", punchline: "You planet.", rating: "clean", category: "science" },
  { setup: "What did one hat say to the other?", punchline: "Stay here, I'm going on ahead.", rating: "clean", category: "dad" },
  { setup: "Why was the belt arrested?", punchline: "It held up a pair of pants.", rating: "clean", category: "dad" },
  { setup: "I lost my mood ring.", punchline: "I don't know how I feel about that.", rating: "clean", category: "one-liner" },
  { setup: "What's a skeleton's least favorite room?", punchline: "The living room.", rating: "clean", category: "halloween" },
  { setup: "Why did the fish blush?", punchline: "Because it saw the ocean's bottom.", rating: "clean", category: "dad" },
  { setup: "What do you call a can opener that doesn't work?", punchline: "A can't opener.", rating: "clean", category: "dad" },
  { setup: "I have a joke about time travel.", punchline: "But you didn't like it.", rating: "clean", category: "science" },
  { setup: "Why did the banana break up with the apple?", punchline: "It found her too appealing to a peach.", rating: "clean", category: "food" },
  { setup: "What's green and sings?", punchline: "Elvis Parsley.", rating: "clean", category: "music" },
  { setup: "Why don't crabs give to charity?", punchline: "Because they're shellfish too.", rating: "clean", category: "animals" },
  { setup: "I asked the gym if they could teach me to do the splits.", punchline: "They said it was a bit of a stretch.", rating: "clean", category: "sports" },
  { setup: "What do you call a lazy kangaroo?", punchline: "A pouch potato.", rating: "clean", category: "animals" },
  { setup: "Why did the baker go to the bank?", punchline: "He needed dough.", rating: "clean", category: "food" },
  { setup: "What's the difference between ignorance and apathy?", punchline: "I don't know and I don't care.", rating: "clean", category: "wordplay" },
  { setup: "Why did the clock get grounded?", punchline: "It tocked too much.", rating: "clean", category: "dad" },
  { setup: "I used to be a tap dancer.", punchline: "Until I fell in the sink.", rating: "clean", category: "one-liner" },
  { setup: "What do you get if you cross a joke with a rhetorical question?", punchline: "", rating: "clean", category: "meta" },
  { setup: "Why do cows have hooves instead of feet?", punchline: "Because they lactose.", rating: "clean", category: "animals" },
  { setup: "What's a frog's favorite drink?", punchline: "Croak-a-cola.", rating: "clean", category: "animals" },
  { setup: "I told my doctor I broke my arm in two places.", punchline: "He told me to stop going to those places.", rating: "clean", category: "one-liner" },
  { setup: "Why was the broom so popular?", punchline: "It swept people off their feet.", rating: "clean", category: "dad" },
  { setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore.", rating: "clean", category: "kids" },
  { setup: "Why did the sausage win the race?", punchline: "It was the wurst of times, then it ketchup.", rating: "clean", category: "food" },
  { setup: "I have a fear of elevators.", punchline: "I'm taking steps to avoid it.", rating: "clean", category: "one-liner" },
  { setup: "What's the difference between a snowman and a snowwoman?", punchline: "Snowballs.", rating: "adult", category: "innuendo" },
  { setup: "Why is a broken drum the best present?", punchline: "You just can't beat it. Unlike my last relationship.", rating: "adult", category: "one-liner" },
  { setup: "A wife asked her husband, 'How would you describe me?'", punchline: "He said 'ABC: adorable, beautiful, cute.' She said 'Thanks!' He said 'Wait, I meant argumentative, bar-hopping, and controlling.'", rating: "adult", category: "marriage" },
  { setup: "Why did the adult coloring book go to therapy?", punchline: "Too many issues to stay inside the lines.", rating: "adult", category: "one-liner" },
  { setup: "I asked my date if she wanted to go somewhere expensive.", punchline: "We went to the gas station.", rating: "adult", category: "dating" },
  { setup: "What's the difference between a lawyer and a trampoline?", punchline: "You take your shoes off before you jump on a trampoline.", rating: "adult", category: "lawyer" },
  { setup: "A man walks into a bar and orders ten shots.", punchline: "The bartender asks why. He says 'I just found out my brother is gay.' Next week he orders twenty. 'I just found out my other brother is gay too.' Third week, thirty shots. Bartender: 'Don't tell me your third brother—' Man: 'No. I just found out I am.'", rating: "adult", category: "bar" },
  { setup: "Why don't they play poker in the jungle?", punchline: "Too many cheetahs. Also the monkeys keep flashing.", rating: "adult", category: "innuendo" },
  { setup: "My therapist told me to write letters to the people I hate, then burn them.", punchline: "I did. Now I don't know what to do with the letters.", rating: "adult", category: "dark" },
  { setup: "What's the secret to a happy marriage?", punchline: "Separate bathrooms and selective hearing.", rating: "adult", category: "marriage" },
  { setup: "A guy is sitting at a bar staring at his drink.", punchline: "A man with a bad attitude comes up, downs the drink, and smirks. The first guy starts crying. 'What's your problem?' 'That was my last hope. That drink was my goodbye.'", rating: "adult", category: "dark" },
  { setup: "Why did the scarecrow get promoted to the late show?", punchline: "He was outstanding in his field and filthy in the green room.", rating: "adult", category: "innuendo" },
  { setup: "I told my partner I wanted to try roleplay.", punchline: "They dressed as a landlord and took all my money.", rating: "adult", category: "dating" },
  { setup: "What's the difference between in-laws and outlaws?", punchline: "Outlaws are wanted.", rating: "adult", category: "marriage" },
  { setup: "A priest, a rabbi, and a minister walk into a bar.", punchline: "The bartender looks up and says, 'What is this, a joke?'", rating: "adult", category: "bar" },
  { setup: "Why did the adult joke get kicked out of the kids' table?", punchline: "It kept trying to slip in a punchline below the belt.", rating: "adult", category: "meta" },
  { setup: "I asked for a dirty martini.", punchline: "The bartender told me a joke about my ex and charged me extra.", rating: "adult", category: "bar" },
  { setup: "What's a pirate's favorite adult beverage?", punchline: "Anything that makes him walk the lime.", rating: "adult", category: "bar" },
  { setup: "My doctor said I needed more exercise, so I started dating again.", punchline: "Turns out running from my problems still counts as cardio.", rating: "adult", category: "dating" },
  { setup: "Why was the belt the most scandalous item in the closet?", punchline: "It had held up too many pants in public.", rating: "adult", category: "innuendo" },
  { setup: "I don't trust stairs.", punchline: "They're always up to something. Same with my roommate.", rating: "adult", category: "one-liner" },
  { setup: "A man is in bed with his wife when she whispers, 'I think I hear a burglar.'", punchline: "He says, 'That's a relief. I thought you were about to ask for a sandwich.'", rating: "adult", category: "marriage" },
  { setup: "What's the difference between a dirty joke and a clean joke?", punchline: "The look on your face when you realize which room you're in.", rating: "adult", category: "meta" },
  { setup: "I joined an adult book club.", punchline: "Nobody's reading. That's the whole point.", rating: "adult", category: "innuendo" },
  { setup: "Why did the chicken cross the road?", punchline: "To prove to the opossum it could be done. The opossum was just playing dead after last night.", rating: "adult", category: "bar" },
  { setup: "My last date said I was too intense.", punchline: "I said 'That's funny, your search history said the same thing.'", rating: "adult", category: "dating" },
  { setup: "What do you call a comedian who only tells adult jokes?", punchline: "Employed after 10pm.", rating: "adult", category: "meta" },
  { setup: "I asked my bartender for something stiff.", punchline: "He handed me the tab.", rating: "adult", category: "bar" },
  { setup: "Why is Monday the most honest day of the week?", punchline: "Because Saturday night already told all the lies.", rating: "adult", category: "bar" },
  { setup: "A couple is having a quiet dinner. She says 'You never listen.'", punchline: "He says 'Sorry, what?'", rating: "adult", category: "marriage" },
];
